/**
 * WCAG 2.2 contrast for text/background pairs in both themes (AA: 4.5 for text, 3 for UI boundaries).
 * Values come from the palette generated by `ng generate @angular/material:theme-color` and the custom tokens
 * in styles.scss. If the brand colour changes, update the table and re-run.
 */
const luminance = (hex: string): number => {
  const channels = (hex.match(/\w\w/g) ?? []).map((part) => {
    const channel = parseInt(part, 16) / 255;

    return channel <= 0.03928 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4;
  });
  const [r = 0, g = 0, b = 0] = channels;

  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};

const contrast = (foreground: string, background: string): number => {
  const [lighter, darker] = [luminance(foreground), luminance(background)].sort((a, b) => b - a) as [number, number];

  return (lighter + 0.05) / (darker + 0.05);
};

type Pair = [foreground: string, background: string];

const PAIRS: [name: string, light: Pair, dark: Pair, minimum: number][] = [
  ['body text', ['#211a14', '#fff8f4'], ['#ede0d6', '#18120d'], 4.5],
  ['muted text on a card', ['#57423a', '#fff1e7'], ['#fcdcd0', '#211a14'], 4.5],
  ['links', ['#a53c02', '#fff8f4'], ['#ffb598', '#18120d'], 4.5],
  ['filled button / badge', ['#ffffff', '#a53c02'], ['#591d00', '#ffb598'], 4.5],
  ['active navigation item', ['#6c3923', '#ffdbce'], ['#ffdbce', '#6c3923'], 4.5],
  ['offline strip', ['#ffffff', '#8a6d1f'], ['#12100e', '#d9b44a'], 4.5],
  ['cart conflicts box', ['#211a14', '#fff4e0'], ['#ede0d6', '#3a2e12'], 4.5],
  ['update banner', ['#fceee4', '#362f28'], ['#362f28', '#ede0d6'], 4.5],
  ['update banner button', ['#370e00', '#ffb598'], ['#ffffff', '#a53c02'], 4.5],
  ['form field border (UI, WCAG 1.4.11)', ['#8b7268', '#fff1e7'], ['#a68b81', '#211a14'], 3],
];

describe('theme contrast (WCAG AA)', () => {
  it.each(PAIRS)('%s', (_name, light, dark, minimum) => {
    expect(contrast(...light)).toBeGreaterThanOrEqual(minimum);
    expect(contrast(...dark)).toBeGreaterThanOrEqual(minimum);
  });
});
